# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SymphenyDemands
                                 A QGIS plugin
 Generate demand profiles of the selected districts ready for Sympheny
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-05
        copyright            : (C) 2020 by Urban Sympheny AG
        email                : carlos.pacheco@sympheny.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SymphenyDemands class from file SymphenyDemands.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Sympheny_demands import SymphenyDemands
    return SymphenyDemands(iface)
